# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EzzydZnyqhUqqR90pNpXu8Om_r5ypD3j

Matplotlib
"""

from matplotlib import pyplot as plt

# (2,5)(3,7)(4,3)(7,6)

x=[2,3,4,7]
y=[5,7,3,6]
plt.plot(x,y)

plt.title("info")
plt.ylabel("girls")
plt.xlabel("boys")

plt.show()

from matplotlib import pyplot as plt

x=[5,8,10]
y=[12,16,6]

plt.bar(x,y,color="g",label="line one")

x1=[6,9,11]
y1=[6,15,7]

plt.bar(x1,y1,color="b",label="line two")

plt.title("info")
plt.ylabel("girls")
plt.xlabel("boys")

#plt.legend()

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = [ 1, 2, 2.5, 3, 4]
y = [ 2, 4, 7, 9 , 15]

plt.plot(x,y,"k:o")
plt.plot(np.unique(x),np.poly1d(np.polyfit(x,y,1))(np.unique(x)))
plt.show()