# -*- coding: utf-8 -*-
"""SignLanguage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r5rBvpcUS8dxBbCl0zBT5fAcxFc1zJ_D
"""

import cv2
import numpy as np
import os

if not os.path.exists("data"):
	os.makedirs("data")
	os.makedirs("data/train")
	os.makedirs("data/test")
	os.makedirs("data/train/0")
	os.makedirs("data/train/1")
	os.makedirs("data/train/2")
	os.makedirs("data/train/3")
	os.makedirs("data/train/4")
	os.makedirs("data/train/5")
	os.makedirs("data/test/0")
	os.makedirs("data/test/1")
	os.makedirs("data/test/2")
	os.makedirs("data/test/3")
	os.makedirs("data/test/4")
	os.makedirs("data/test/5")

camera = cv2.VideoCapture(0)
mode = 'train'
directory = 'data/' + mode + '/'

while True:
	success,frame = camera.read()
	frame = cv2.flip(frame,1)

	count = {
		'zero' : len(os.listdir(directory+'0/')),
		'one' : len(os.listdir(directory+'1/')),
		'two' : len(os.listdir(directory+'2/')),
		'three' : len(os.listdir(directory+'3/')),
		'four' : len(os.listdir(directory+'4/')),
		'five' : len(os.listdir(directory+'5/')),
	}

	cv2.putText(frame,"MODE : " + mode,(10,50),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"ZERO : " + str(count['zero']),(10,70),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"ONES : " + str(count['one']),(10,90),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"TWOS : " + str(count['two']),(10,110),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"THRE : " + str(count['three']),(10,130),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"FOUR : " + str(count['four']),(10,150),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)
	cv2.putText(frame,"FIVE : " + str(count['five']),(10,170),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0),2)

	x1 = 350
	y1 = 10

	x2 = 600
	y2 = 310

	cv2.rectangle(frame,(x1-2,y1-2),(x2+2,y2+2),(0,255,0),2)
  #chotu = frame[y1:y2,x1:x2]
	#chotu = cv2.resize(chotu,(64,64))
	#chotu = cv2.cvtColor(chotu,cv2.COLOR_BGR2GRAY)
	
	#_, chotu = cv2.threshold(chotu, 120, 255, cv2.THRESH_BINARY)

	#cv2.imshow("Chotu",chotu)
	cv2.imshow("Frame",frame)
	interrupt = cv2.waitKey(10)

	if interrupt & 0xFF == 27:
		break
	if interrupt & 0xFF == ord('0'):
		cv2.imwrite(directory+'0/'+str(count['zero'])+'.jpg',chotu)
	if interrupt & 0xFF == ord('1'):
		cv2.imwrite(directory+'1/'+str(count['one'])+'.jpg',chotu)
	if interrupt & 0xFF == ord('2'):
		cv2.imwrite(directory+'2/'+str(count['two'])+'.jpg',chotu)
	if interrupt & 0xFF == ord('3'):
		cv2.imwrite(directory+'3/'+str(count['three'])+'.jpg',chotu)
	if interrupt & 0xFF == ord('4'):
		cv2.imwrite(directory+'4/'+str(count['four'])+'.jpg',chotu)
	if interrupt & 0xFF == ord('5'):
		cv2.imwrite(directory+'5/'+str(count['five'])+'.jpg',chotu)


camera.release()
cv2.destroyAllWindows()