# -*- coding: utf-8 -*-
"""Tensor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1seyrYLHw1ZNYSPhMDSyHPYCN-_fT14DX
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib
import tensorflow.compat.v2.feature_column as fc
import tensorflow as tf

from __future__ import absolute_import ,division ,print_function ,unicode_literals

"""tensor = DataType + shape

Datatypes = string,int16,float64
"""

import tensorflow as tf

name = tf.Variable("harshit",tf.string)
roll = tf.Variable(88,tf.int16)
marks = tf.Variable(66.5,tf.float64)

"""# Rank and shape"""

rank1 = tf.Variable(["harshit","geet","gourav"],tf.string)
rank2 = tf.Variable([["harshit","geet","gourav"],["gracy","deesha","himanshu"]],tf.string)

tf.rank(rank1)
rank2.shape

tensor1 = tf.ones([1,2,3])
print(tensor1)
#[[[1,1,1],[1,1,1]]]

tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
#[[[1],[1],[1]],[[1],[1],[1]]]

tensor3 = tf.reshape(tensor1,[3,-1])
print(tensor3)

matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

"""Titanic"""

# Load dataset.
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv') # training data
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv') # testing data

y_train = dftrain.pop('survived')
y_test = dfeval.pop('survived')

dftrain.head()
#dftrain.describe()

dftrain.age.hist(bins=20)

dftrain.sex.value_counts().plot(kind='barh')

dftrain['class'].value_counts().plot(kind='barh')

pd.concat([dftrain, y_train], axis=1).groupby('sex').survived.mean().plot(kind='barh').set_xlabel('% survive')

"""After analyzing this information, we should notice the following:

-Most passengers are in their 20's or 30's
-Most passengers are male
-Most passengers are in "Third" class
-Females have a much higher chance of survival
"""